src/TennisBookings/Areas/Admin/Controllers/CourtsController.cs
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using TennisBookings.Areas.Admin.Models;

namespace TennisBookings.Areas.Admin.Controllers;

[Area("Admin")]
[Route("Admin/[controller]")]
[Authorize(Roles = "Admin")]
public class CourtsController : Controller
{
	private readonly ICourtBookingService _courtBookingService;
	private readonly IUtcTimeService _utcTimeService;

	public CourtsController(ICourtBookingService courtBookingService, IUtcTimeService utcTimeService)
	{
		_courtBookingService = courtBookingService;
		_utcTimeService = utcTimeService;
	}

	[HttpGet]
	[Route("Bookings/Upcoming")]
	public async Task<ActionResult> WeeklyBookings()
	{
		var bookings = await _courtBookingService
			.BookingsUntilDateAsync(_utcTimeService.CurrentUtcDateTime.GetEndOfWeek().AddDays(7));

		var bookingsViewModel = bookings.Select(x => new CourtBookingViewModel
		{
			BookingId = x.Id,
			CourtName = x.Court!.Name,
			StartDateTime = x.StartDateTime,
			EndDateTime = x.EndDateTime,
			MemberName = $"{x.Member!.Forename} {x.Member.Surname}"
		}).GroupBy(x => x.StartDateTime.Date);

		var viewModel = new BookingListerViewModel
		{
			CourtBookings = bookingsViewModel,
			EndOfWeek = _utcTimeService.CurrentUtcDateTime.GetEndOfWeek().AddDays(7)
		};

		if (TempData.TryGetValue("BookingCancelled", out var successObject) is bool success)
		{
			viewModel.CancelSuccessful = success;
		}

		return View(viewModel);
	}

	[HttpGet]
	[Route("Booking/{bookingId:int}/Cancel")]
	public async Task<ActionResult> CancelBooking(int bookingId)
	{
		var courtBooking = await _courtBookingService.LoadBooking(bookingId);

		if (courtBooking == null)
			return NotFound();

		var viewModel = new CancelBookingConfirmationViewModel
		{
			BookingId = bookingId,
			CourtName = courtBooking.Court!.Name,
			MemberName = $"{courtBooking.Member!.Forename} {courtBooking.Member.Surname}",
			Date = courtBooking.StartDateTime.Date,
			StartTime = courtBooking.StartDateTime.Hour.To12HourClockString(),
			EndTime = courtBooking.EndDateTime.Hour.To12HourClockString()
		};

		return View(viewModel);
	}

	[HttpPost]
	[Route("Booking/{bookingId:int}/Cancel")]
	public async Task<ActionResult> CancelBookingConfirmation(int bookingId, string submitButton)
	{
		if (submitButton == "Cancel")
		{
			return RedirectToAction("WeeklyBookings");
		}

		await _courtBookingService.CancelBooking(bookingId);

		TempData["BookingCancelled"] = true;

		return RedirectToAction("WeeklyBookings");
	}

	[Route("Maintenance/Upcoming")]
	public async Task<ActionResult> UpcomingMaintenance([FromServices] ICourtMaintenanceService courtMaintenanceService)
	{
		var maintenanceSchedules = await courtMaintenanceService.GetUpcomingMaintenance();

		var maintenanceViewModels = maintenanceSchedules.Select(x => new CourtMaintenanceViewModel
		{
			CourtName = x.Court.Name,
			StartDateTime = x.StartDate,
			EndDateTime = x.EndDate,
			Title = x.WorkTitle,
			CourtIsClosed = x.CourtIsClosed
		}).GroupBy(x => x.StartDateTime.Date);

		var viewModel = new MaintenanceListerViewModel { ScheduledMaintenanceWork = maintenanceViewModels };

		return View(viewModel);
	}
}

src/TennisBookings/Areas/Admin/Controllers/StaffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TennisBookings.Areas.Admin.Controllers;

[Area("Admin")]
[Route("Admin/Staff")]
[Authorize(Roles = "Admin")]
public class StaffController : Controller
{
	[Route("Add")]
	public ViewResult AddStaffMember()
	{
		return View();
	}
}

src/TennisBookings/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tennis by the Sea (Admin)</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">Tennis by the Sea (Admin)</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Courts" asp-action="WeeklyBookings">Bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Courts" asp-action="UpcomingMaintenance">Maintenance</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Staff" asp-action="AddStaffMember">Staff</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Member Site</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Tennis by the Sea
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>